export interface IUserRegister {
  firstName: string,
  lastName: string,
  email: string,
  registrationType: string,
  password: string,
  confirmedPassword: string,
  gender: string,
  dateOfBirth: Date,
  receiveClubEmails: boolean,
  securityQuestion: string,
  securityAnswer: string,
  streetAddress: string,
  accommodation: string,
  city: string,
  province: string,
  postalCode: string,
  phone: string,
  wtcAgreement: string,
  wtcAgreement2: string,
  covidAgreement: string
}
