export interface Profile {
  role: string,
  clubCardId: string,
  firstName: string,
  lastName: string,
  email: string,
  subType: string,
  gender: string,
  phone: string,
  dateOfBirth: Date,
  rating: string,
  receiveClubEmails: boolean,
  shareMyEmail: boolean,
  shareMyPhone: boolean,
  twitter: string,
  instagram: string,
  facebook: string,
}
